version: "3.9"

services:
  postgres-as:
    image: postgres:16
    container_name: postgres-as
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: meubanco
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - net-as-java

  pgadmin-as:
    image: dpage/pgadmin4
    container_name: pgadmin-as
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - net-as-java

networks:
  net-as-java:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:


#  PARA RODAR DOCKER-COMPOSE: sudo docker compose up -d

#  host name: server-as
#  host name: pgadmin-as
#  database: meubanco
#  user e senha: postgres

